# Generated by Django 5.0.6 on 2024-07-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
